export const GET_GAME_LIST = 'GET_GAME_LIST';
export const GET_GAME_SLIDER = 'GET_GAME_SLIDER';
export const GET_PC_TRENDING_GAME = 'GET_PC_TRENDING_GAME';
export const GET_PS4_TRENDING_GAME = 'GET_PS4_TRENDING_GAME';
export const GET_XBOX_ONE_TRENDING_GAME = 'GET_XBOX_ONE_TRENDING_GAME';
export const GET_GAME_DETAILS = 'GET_GAME_DETAILS';